#!/usr/bin/env python3
"""Refresh only the managed sharing metadata in both static homepages."""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from social_metadata import HOME_PAGES, render_social_metadata


def main():
    for filename, info in HOME_PAGES.items():
        path = ROOT / filename
        page = path.read_text(encoding="utf-8")
        block = ("  <!-- Social metadata: generated by scripts/update_home_social_metadata.py -->\n"
                 + render_social_metadata(**info) + "\n  <!-- End social metadata -->")
        pattern = r"  <!-- Social metadata:.*?<!-- End social metadata -->"
        if re.search(pattern, page, flags=re.S):
            page = re.sub(pattern, lambda _: block, page, count=1, flags=re.S)
        else:
            page, count = re.subn(r'  <meta name="description"[^>]+/>',
                                  lambda m: m.group() + "\n" + block, page, count=1)
            if count != 1:
                raise ValueError(f"Cannot locate description meta tag: {filename}")
        path.write_text(page, encoding="utf-8")
        print(f"Updated sharing metadata: {filename}")


if __name__ == "__main__":
    main()
